piVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp-deployment
  labels:
    app: nodejsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
      - name: nodejsapp
        image: rohannegi11/nodejsapp:latest
        ports:
        - containerPort: 3000
